[tool.pyright]
reportAny = false
reportExplicitAny = false
reportMissingTypeStubs = false
reportImplicitRelativeImport = false
reportUnknownArgumentType =  false
reportUnknownVariableType =  false
reportUnknownMemberType =  false
reportUnusedCallResult = false
reportUnknownParameterType = false
reportMissingTypeArgument = false
reportMissingParameterType = false
reportUnannotatedClassAttribute = false